# Generated by Django 5.0.6 on 2024-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='licitacao',
            fields=[
                ('numProcess', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=15)),
                ('objeto', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
