# Generated by Django 5.0.6 on 2024-07-23 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddingContracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='dataEmissao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
