# Generated by Django 5.0.6 on 2024-07-07 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddingContracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cnpj', models.TextField()),
                ('endereco', models.TextField()),
                ('num', models.TextField()),
                ('bairro', models.TextField()),
                ('cep', models.TextField()),
                ('telefone', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='licitacao',
            name='objeto',
        ),
        migrations.AddField(
            model_name='licitacao',
            name='assunto',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('assuntoDetalhado', models.TextField(max_length=200)),
                ('dataInicial', models.DateField(auto_now_add=True)),
                ('dataFinal', models.DateField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('licitacao_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingContracts.licitacao')),
                ('fornecedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingContracts.fornecedor')),
            ],
        ),
    ]
