# Generated by Django 5.0.6 on 2024-08-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddingContracts', '0002_notafiscal_dataemissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='assuntoDetalhado',
            field=models.TextField(max_length=200, verbose_name='Detalhe do contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='assunto',
            field=models.CharField(max_length=200, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='Categoria'),
        ),
    ]
