# Generated by Django 5.0.6 on 2024-08-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddingContracts', '0003_alter_contrato_assuntodetalhado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacao',
            name='numProcess',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
